/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javatest;

public class Library {
    public boolean someLibraryMethod() {
        MathStuff stuff=new MathStuff(true,1,1);
        stuff.calcValue();
        return true;
    }
    private boolean sign;
    private double mantissa;
    private int exponent;
}
