package org.argouml.ui.theme;

import javax.swing.plaf.FontUIResource;

public class ThemeFonts {
    private final FontUIResource controlFont = ...
    private final FontUIResource systemFont = ...
    private final FontUIResource windowTitleFont = ...
    private final FontUIResource userFont = ...
    private final FontUIResource smallFont = ...
    ...
}